# Generated by Django 5.0.1 on 2024-02-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('price', models.FloatField(default=10)),
                ('product_image', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('rating', models.FloatField()),
                ('available_quentity', models.IntegerField()),
                ('pending_quentity', models.IntegerField()),
            ],
        ),
    ]
