# Generated by Django 5.0.1 on 2024-02-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='compney_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
