# Generated by Django 5.0.2 on 2024-03-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_products_created_at_alter_products_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default='2024-03-09 11:26:32'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(default='2024-03-09 11:26:32'),
        ),
    ]
