# Generated by Django 5.0.2 on 2024-03-10 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_usercartmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=100)),
                ('line2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.BigIntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usercartmodel',
            options={'verbose_name_plural': 'User Carts'},
        ),
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('order_placed_at', models.DateTimeField(auto_now_add=True)),
                ('product_total_quantity', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_quantity', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('CASH_ON_DELIVERY', 'CASH_ON_DELIVERY'), ('UPI', 'UPI'), ('NET_BANKING', 'NET_BANKING')], default='CASH_ON_DELIVERY', max_length=20)),
                ('total_amount', models.FloatField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.useraddress')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
